### ISSUE TITLE
refactor export_as_txt from rtables tand rlistings, and move it to formatters

### ISSUE THREAD

**Issue by shajoezhu** [insightsengineering/NEST-roadmap#84]

**Comment by nikolas-burkoff** [comment]
Note this will require a change to teal.widgets https://github.com/insightsengineering/teal.widgets/blob/main/R/table_with_settings.R#L217 unless you re-export it through rtables - please co-ordinate with @donyunardi so that we don't say release teal.widgets and then it not work with a new release of rtables

**Comment by lcd2yyz** [comment]
@shajoezhu Any potential timeline you can provide on this?

**Comment by shajoezhu** [comment]
hi @lcd2yyz , we planned this in sprint 3 for the next PI, but during the PI, Vincent identified this as a less-priority item, if plan changes, I will let you know.

**Comment by Melkiades** [comment]
Completed @lcd2yyz
